services:

  soundgnome:
    image: ghcr.io/richyk1/soundgnome:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
        - SOUNDGNOME__GENERAL__BASE_LIBRARY_DIR=/app/library
        - SOUNDGNOME__GENERAL__TEMP_DOWNLOAD_DIR=/app/temp
        - SOUNDGNOME__DATABASE__URL=/data/soundgnome.db
    volumes:
      - ./data:/data
      - ./library:/app/library
      - ./temp:/app/temp
      - ./config.toml:/app/config.toml:ro
    restart: unless-stopped
