services:

  soundome:
    image: ghcr.io/barthofu/soundome:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
        - SOUNDOME__GENERAL__BASE_LIBRARY_DIR=/app/library
        - SOUNDOME__GENERAL__TEMP_DOWNLOAD_DIR=/app/temp
        - SOUNDOME__DATABASE__URL=/data/soundome.db
    volumes:
      - ./data:/data
      - ./library:/app/library
      - ./temp:/app/temp
      - ./config.toml:/app/config.toml:ro
    restart: unless-stopped
